### ISSUE TITLE
Using this for notifications stored in www and managing other sounds

### ISSUE THREAD

**Issue by epetre** [TongZhangzt/cordova-plugin-native-ringtones#2]
Hello, nice job on the plugin, it's simple and to the point. 
I'm trying to make it work with short notifications that are stored in the www folder and managed to make it work for Android with a [few changes](https://github.com/epetre/cordova-plugin-native-ringtones).

Still didn't manage to make it work for ios but please let me know if you have any tips or thoughts.

**Comment by TongZhangzt** [comment]
Hi, Thank you epetre.

Do you mean that you want to play custom ringtone stored in the www folder in your project? If this is the case, in fact the plugin now can play custom ringtone stored in www folder on both IOS and Android platform. I forgot to add this feature in the readme.

**Comment by msd117** [comment]
Hey @TongZhangzt this seems to not work somehow ... if possible can you please share how to use to play sounds in www folder
