### ISSUE TITLE
Looping & Stopping Ringtones

### ISSUE THREAD

**Issue by cktg** [TongZhangzt/cordova-plugin-native-ringtones#3]
Hi, 

Thanks for sharing the codes.

I manage to play looping ringtone in android by adding "ringtoneSound.setLooping(true);"  after line 96 in NativeRingtones.java . However, I couldn't figure a way to stop it with cordova.plugins.NativeRingtones.playRingtone.

I tried Changing ringtoneSound.stop() to ringtoneSound.release() but that didn't work. 

Any idea why it is not working? Thanks

**Comment by TongZhangzt** [comment]
Hi. I guess you can try: 
`ringtoneSound.setLooping(true);
  ringtoneSound.prepare();
  ringtoneSound.start();`
then try to stop it by:
`ringtoneSound.stop();
ringtoneSound.reset();`
the MediaPlayer cycle should be reset()-->setDataSource(path)-->prepare()-->start()-->stop()--reset()-->...

I guess another reason maybe you should use the same `ringtoneSound` object in the `start` and  `stop` function. Maybe add `private MediaPlayer ringtoneSound;`.

**Comment by anupamgovind1981** [comment]
How I can do it same for Ionic 3? I am looking solution for both - iOS & Android

**Comment by TongZhangzt** [comment]
@anupamgovind1981 I didn't try Ionic 3 yet, but I tried Ionic 2, it can work.

**Comment by agovind81** [comment]
Please suggest changes for iOS.
