### ISSUE TITLE
Can this plugin be used to access notification sounds also (ios)?

### ISSUE THREAD

**Issue by frey1esm** [TongZhangzt/cordova-plugin-native-ringtones#5]

**Comment by TongZhangzt** [comment]
Hi, the getRingtone() function get the list of all system sounds on IOS, check it here: https://github.com/TUNER88/iOSSystemSoundsLibrary

**Comment by frey1esm** [comment]
Unfortunately the getRingtone() function does not return the ringtones (eg. Apex, Beacon, etc) nor text tones (eg. Aurora, Bamboo, etc) that are the standards tones on ios.  It looks like just the "Classic" ringtones are returned along with other system sounds. If you look at [https://github.com/TUNER88/iOSSystemSoundsLibrary](https://github.com/TUNER88/iOSSystemSoundsLibrary) you will see Aurora and the others listed at the bottom with direct system references only, but not in the List of SystemSoundIDs.

**Comment by TongZhangzt** [comment]
Sorry for the late response, this https://github.com/TUNER88/iOSSystemSoundsLibrary repo shows the list in iOS 7.0.2. Based on this note on Apple's docs : https://developer.apple.com/documentation/audiotoolbox/1405202-audioservicesplayalertsound?preferredLanguage=occ, we don't have access the "internal" sound clips: 
`Note System-supplied alert sounds and system-supplied user-interface sound effects are not available to your iOS application. For example, using the kSystemSoundID_UserPreferredAlert constant as a parameter to the AudioServicesPlayAlertSound function will not play anything.`
