### ISSUE TITLE
device ringtone list is not matching with plugin array list...

### ISSUE THREAD

**Issue by pragatiy** [TongZhangzt/cordova-plugin-native-ringtones#8]
Is there any suggestion to find it out ?

**Comment by TongZhangzt** [comment]
@pragatiy There are three kinds of ringtones for Android: 'notification', 'alarm', 'ringtone', default 'notification'. For IOS, check the list here: https://github.com/TUNER88/iOSSystemSoundsLibrary

**Comment by pragatiy** [comment]
Thanks @TongZhangzt . now i got the list of notification ringtone in Android. is it possible to fetch the ringtones by plugin ?

**Comment by TongZhangzt** [comment]
@pragatiy I didn't try to fetch the ringtones, this plugin can only play and stop play the given ringtone. But if you have got the list of notification ringtone (URI list), I guess you could use cordova-plugin-file plugin to do that.

**Comment by pragatiy** [comment]
In ios its showing some additional  ringtones which are not matching with the device notification ringtone .
how to can get only those notification are there in the device.

**Comment by TongZhangzt** [comment]
@pragatiy You can build some filter function after you got the list

**Comment by merjana** [comment]
have same problem here, it does not show the ringtons

**Comment by TongZhangzt** [comment]
@merjana Android or IOS? For Android, you need to specify 'notification', 'alarm', 'ringtone'.

**Comment by merjana** [comment]
where to specify exactly ? i tried this.ringtones.getRingtone("alarm"); but it didn't work

**Comment by TongZhangzt** [comment]
@merjana at the third parameter of the function:
`cordova.plugins.NativeRingtones.getRingtone(function(success) {
                ringtones = success;
            },
            function(err) {
                alert(err);
            }, "alarm");`
