### ISSUE TITLE
Ringtone doesn't play after playing 10 sounds

### ISSUE THREAD

**Issue by shivaprabhu** [TongZhangzt/cordova-plugin-native-ringtones#9]
I have a feature where i show all the ringtones to the user, when the user selects a sound, it plays. The problem is after playing around 10 sounds, no further sounds are heard.By the way this is on Android. Can you please take a look at this? Thanks!

**Comment by TongZhangzt** [comment]
Did you call stop function to stop playing the last ringtone when user select a new ringtone?

**Comment by shivaprabhu** [comment]
I did, even then the issue persists
Motorola G4, i can here up to 32 sounds, then it fails.- android -v 7.0
Redmi Note 5, i can hear up to 14 sounds, then it fails.- android- v 7.1.0

**Comment by TongZhangzt** [comment]
@shivaprabhu I don't have the specific devices to test. But I didn't see any changes in 'MediaPlayer' after v7.0.0. Did you try with other devices? And you can also use 'cordova-plugin-media' to play the ringtone after you get the list.

**Comment by shivaprabhu** [comment]
Yeah, i tried that as well but it's the same
